Final Project - Machine Learning

## Upload and Prepare the data

In [5]:
#import dependencies
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced
from sklearn.preprocessing import StandardScaler

In [6]:
# add import warnigns to skip any warning messages on the screen
import warnings
warnings.filterwarnings('ignore')

In [7]:
#create file direcotry
file_dir = 'C:/Users/larys/DAB/Final_Project/Resources/'

In [8]:
#import the csv files
shot_log = pd.read_csv(f'{file_dir}joined_shots_2013.csv', index_col=0)
#stats = pd.read_csv(f'{file_dir}players_stats.csv', index_col=0)

## SHOT LOG dataset

In [9]:
shot_log

CLOSEST_DEFENDER  CLOSEST_DEFENDER_PLAYER_ID  CLOSE_DEF_DIST  \
0               Turner, Evan                    202323.0             1.9   
1               Turner, Evan                    202323.0             3.2   
2   Carter-Williams, Michael                    203487.0             3.5   
3             Brown, Lorenzo                    203485.0             3.6   
0               Cole, Norris                    202708.0             3.7   
..                       ...                         ...             ...   
0                 Asik, Omer                    201600.0             2.3   
0          Jennings, Brandon                    201943.0             1.8   
1                Smith, Josh                      2746.0             7.1   
2                Smith, Josh                      2746.0             1.1   
3               Monroe, Greg                    202328.0             5.2   

    DRIBBLES  FGM  FINAL_MARGIN GAME_CLOCK   GAME_ID  GAME_ID.1 LOCATION  ...  \
0       17.0  0.0          10.0       8:09  21300165   21300165        A  ...   
1        0.0  1.0          10.0       9:10  21300165   21300165        A  ...   
2        0.0  0.0          10.0       8:36  21300165   21300165        A  ...   
3       19.0  0.0          10.0       0:23  21300165   21300165        A  ...   
0        0.0  1.0          -7.0      11:43  21300230   21300230        H  ...   
..       ...  ...           ...        ...       ...        ...      ...  ...   
0        1.0  0.0           8.0       0:17  21300862   21300862        H  ...   
0        2.0  0.0           9.0       9:31  21300607   21300607        A  ...   
1        0.0  0.0           9.0       7:50  21300607   21300607        A  ...   
2        3.0  0.0           9.0       7:00  21300607   21300607        A  ...   
3        1.0  0.0           9.0       6:54  21300607   21300607        A  ...   

           ACTION_TYPE       SHOT_TYPE        SHOT_ZONE_BASIC  \
0            Jump Shot  2PT Field Goal  In The Paint (Non-RA)   
1            Jump Shot  3PT Field Goal      Above the Break 3   
2            Jump Shot  3PT Field Goal      Above the Break 3   
3            Jump Shot  3PT Field Goal      Above the Break 3   
0            Jump Shot  3PT Field Goal      Above the Break 3   
..                 ...             ...                    ...   
0   Reverse Layup Shot  2PT Field Goal        Restricted Area   
0   Fadeaway Jump Shot  2PT Field Goal              Mid-Range   
1            Jump Shot  3PT Field Goal      Above the Break 3   
2   Driving Layup Shot  2PT Field Goal        Restricted Area   
3            Jump Shot  3PT Field Goal      Above the Break 3   

           SHOT_ZONE_AREA  SHOT_ZONE_RANGE  SHOT_DISTANCE  LOC_X  LOC_Y  \
0               Center(C)  Less Than 8 ft.            6.0  -40.0   53.0   
1   Right Side Center(RC)          24+ ft.           26.0  182.0  195.0   
2   Right Side Center(RC)          24+ ft.           26.0  159.0  206.0   
3               Center(C)          24+ ft.           27.0  -15.0  274.0   
0    Left Side Center(LC)          24+ ft.           24.0 -149.0  198.0   
..                    ...              ...            ...    ...    ...   
0               Center(C)  Less Than 8 ft.            2.0  -22.0    8.0   
0           Right Side(R)        16-24 ft.           18.0  177.0   64.0   
1    Left Side Center(LC)          24+ ft.           26.0 -201.0  167.0   
2               Center(C)  Less Than 8 ft.            0.0    6.0    6.0   
3    Left Side Center(LC)          24+ ft.           25.0 -164.0  194.0   

   SHOT_ATTEMPTED_FLAG  SHOT_MADE_FLAG  
0                  1.0             0.0  
1                  1.0             1.0  
2                  1.0             0.0  
3                  1.0             0.0  
0                  1.0             1.0  
..                 ...             ...  
0                  1.0             0.0  
0                  1.0             0.0  
1                  1.0             0.0  
2                  1.0            

In [10]:
#Split the Data into Training and Testing

In [11]:
shot_log.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 200963 entries, 0 to 3
Data columns (total 40 columns):
 #   Column                      Non-Null Count   Dtype  
---  ------                      --------------   -----  
 0   CLOSEST_DEFENDER            200963 non-null  object 
 1   CLOSEST_DEFENDER_PLAYER_ID  200963 non-null  float64
 2   CLOSE_DEF_DIST              200963 non-null  float64
 3   DRIBBLES                    200963 non-null  float64
 4   FGM                         200963 non-null  float64
 5   FINAL_MARGIN                200963 non-null  float64
 6   GAME_CLOCK                  200963 non-null  object 
 7   GAME_ID                     200963 non-null  int64  
 8   GAME_ID.1                   200963 non-null  int64  
 9   LOCATION                    200963 non-null  object 
 10  MATCHUP                     200963 non-null  object 
 11  PERIOD                      200963 non-null  float64
 12  PERIOD.1                    200963 non-null  float64
 13  PTS                

In [12]:
# check all numeric columns
shot_log.describe()

CLOSEST_DEFENDER_PLAYER_ID  CLOSE_DEF_DIST       DRIBBLES  \
count               200963.000000   200963.000000  200963.000000   
mean                151083.898748        4.183973       1.920339   
std                  82249.173922        2.726702       3.408023   
min                    708.000000        0.000000       0.000000   
25%                 101131.000000        2.300000       0.000000   
50%                 201599.000000        3.700000       0.000000   
75%                 202693.000000        5.300000       2.000000   
max                 203816.000000       52.300000      34.000000   

                 FGM   FINAL_MARGIN       GAME_ID     GAME_ID.1  \
count  200963.000000  200963.000000  2.009630e+05  2.009630e+05   
mean        0.454581      -0.033444  2.130062e+07  2.130062e+07   
std         0.497944      13.510571  3.543158e+02  3.543158e+02   
min         0.000000     -48.000000  2.130000e+07  2.130000e+07   
25%         0.000000      -9.000000  2.130031e+07  2.130031e+07   
50%         0.000000      -1.000000  2.130062e+07  2.130062e+07   
75%         1.000000       9.000000  2.130092e+07  2.130092e+07   
max         2.000000      48.000000  2.130123e+07  2.130123e+07   

              PERIOD       PERIOD.1            PTS  ...      PLAYER_ID  \
count  200963.000000  200963.000000  200963.000000  ...  200963.000000   
mean        2.483746       2.483736       1.002413  ...  150488.014426   
std         1.140326       1.140322       1.131280  ...   82797.168385   
min         1.000000       1.000000       0.000000  ...     708.000000   
25%         1.000000       1.000000       0.000000  ...  101127.000000   
50%         2.000000       2.000000       0.000000  ...  201593.000000   
75%         3.000000       3.000000       2.000000  ...  202689.000000   
max         7.000000       7.000000       4.000000  ...  203816.000000   

         PLAYER_ID.1       TEAM_ID  MINUTES_REMAINING  SECONDS_REMAINING  \
count  200963.000000  2.009630e+05      200963.000000      200963.000000   
mean   150488.014426  1.610613e+09           5.326349          28.738141   
std     82797.168385  8.662363e+00           3.459346          17.459695   
min       708.000000  1.610613e+09           0.000000           0.000000   
25%    101127.000000  1.610613e+09           2.000000          14.000000   
50%    201593.000000  1.610613e+09           5.000000          29.000000   
75%    202689.000000  1.610613e+09           8.000000          44.000000   
max    203816.000000  1.610613e+09          12.000000          59.000000   

       SHOT_DISTANCE          LOC_X          LOC_Y  SHOT_ATTEMPTED_FLAG  \
count  200963.000000  200963.000000  200963.000000             200963.0   
mean       12.303230      -0.449496      80.807606                  1.0   
std         9.848454     109.038567      87.439261                  0.0   
min         0.000000    -250.000000     -51.000000                  1.0   
25%         2.000000     -54.000000       9.000000                  1.0   
50%        13.000000       1.000000      41.000000                  1.0   
75%        22.000000      51.000000     153.000000                  1.0   
max        86.000000     250.000000     865.000000                  1.0   

       SHOT_MADE_FLAG  
count   200963.000000  
mean         0.454576  
std          0.497934  
min          0.000000  
25%          0.000000  
50%          0.000000  
75%          1.000000  
max          1.000000  

[8 rows x 26 columns]

In [13]:
# check all non-numeric columns
shot_log.describe(include=np.object)

CLOSEST_DEFENDER GAME_CLOCK LOCATION                   MATCHUP  \
count            200963     200963   200963                    200963   
unique              479        721        2                      2452   
top     Jordan, DeAndre       0:01        A  NOV 11, 2013 - TOR @ HOU   
freq               1341       1222   100592                       114   

       SHOT_RESULT       W          GRID_TYPE   PLAYER_NAME   EVENT_TYPE  \
count       200963  200963             200963        200963       200963   
unique           2       2                  1           479            2   
top         missed       L  Shot Chart Detail  Kevin Durant  Missed Shot   
freq        109610  101219             200963          1677       109610   

       ACTION_TYPE       SHOT_TYPE  SHOT_ZONE_BASIC SHOT_ZONE_AREA  \
count       200963          200963           200963         200963   
unique          50               2                7              6   
top      Jump Shot  2PT Field Goal  Restricted Area      Center(C)   
freq        106933          148867            64946         109766   

        SHOT_ZONE_RANGE  
count            200963  
unique                5  
top     Less Than 8 ft.  
freq              84805

In [14]:
# Clean version of correlation matrix (visualize)
corr = shot_log.corr()
corr.style.background_gradient(cmap='coolwarm').set_precision(2)
# 'RdBu_r' & 'BrBG' are other good diverging colormaps

In [15]:
shot_log.columns


Index(['CLOSEST_DEFENDER', 'CLOSEST_DEFENDER_PLAYER_ID', 'CLOSE_DEF_DIST',
       'DRIBBLES', 'FGM', 'FINAL_MARGIN', 'GAME_CLOCK', 'GAME_ID', 'GAME_ID.1',
       'LOCATION', 'MATCHUP', 'PERIOD', 'PERIOD.1', 'PTS', 'PTS_TYPE',
       'SHOT_CLOCK', 'SHOT_DIST', 'SHOT_NUMBER', 'SHOT_RESULT', 'TOUCH_TIME',
       'W', 'GRID_TYPE', 'GAME_EVENT_ID', 'PLAYER_ID', 'PLAYER_ID.1',
       'PLAYER_NAME', 'TEAM_ID', 'MINUTES_REMAINING', 'SECONDS_REMAINING',
       'EVENT_TYPE', 'ACTION_TYPE', 'SHOT_TYPE', 'SHOT_ZONE_BASIC',
       'SHOT_ZONE_AREA', 'SHOT_ZONE_RANGE', 'SHOT_DISTANCE', 'LOC_X', 'LOC_Y',
       'SHOT_ATTEMPTED_FLAG', 'SHOT_MADE_FLAG'],
      dtype='object')

### Prepare file

In [16]:
#drop columns
shot_log = shot_log.drop(columns = ['PERIOD', 'MATCHUP', 'PERIOD.1', 'PLAYER_ID.1', 'W', 'GAME_ID.1', 'SHOT_ATTEMPTED_FLAG',\
                                          'GAME_CLOCK', 'CLOSEST_DEFENDER_PLAYER_ID', 'SHOT_CLOCK', 'FINAL_MARGIN', 'EVENT_TYPE',\
                                          'FGM', 'SHOT_MADE_FLAG', 'GRID_TYPE', 'TEAM_ID', 'GAME_EVENT_ID', 'MINUTES_REMAINING',\
                                         'PLAYER_ID', 'GAME_ID', 'SHOT_NUMBER', 'CLOSEST_DEFENDER'])
shot_log

CLOSE_DEF_DIST  DRIBBLES LOCATION  PTS  PTS_TYPE  SHOT_DIST SHOT_RESULT  \
0              1.9      17.0        A  0.0       2.0        7.7      missed   
1              3.2       0.0        A  3.0       3.0       23.5        made   
2              3.5       0.0        A  0.0       3.0       25.7      missed   
3              3.6      19.0        A  0.0       3.0       24.7      missed   
0              3.7       0.0        H  3.0       3.0       25.2        made   
..             ...       ...      ...  ...       ...        ...         ...   
0              2.3       1.0        H  0.0       2.0        1.3      missed   
0              1.8       2.0        A  0.0       2.0       13.7      missed   
1              7.1       0.0        A  0.0       3.0       22.9      missed   
2              1.1       3.0        A  0.0       2.0        3.1      missed   
3              5.2       1.0        A  0.0       3.0       25.0      missed   

    TOUCH_TIME    PLAYER_NAME  SECONDS_REMAINING         ACTION_TYPE  \
0         13.5  Dwight Buycks                6.0           Jump Shot   
1          1.4  Dwight Buycks                7.0           Jump Shot   
2          1.3  Dwight Buycks               33.0           Jump Shot   
3         14.5  Dwight Buycks               21.0           Jump Shot   
0          1.0  Dwight Buycks               41.0           Jump Shot   
..         ...            ...                ...                 ...   
0          0.9  Hedo Turkoglu               15.0  Reverse Layup Shot   
0          3.2  Hedo Turkoglu               28.0  Fadeaway Jump Shot   
1          1.2  Hedo Turkoglu               48.0           Jump Shot   
2          3.1  Hedo Turkoglu               56.0  Driving Layup Shot   
3          2.1  Hedo Turkoglu               49.0           Jump Shot   

         SHOT_TYPE        SHOT_ZONE_BASIC         SHOT_ZONE_AREA  \
0   2PT Field Goal  In The Paint (Non-RA)              Center(C)   
1   3PT Field Goal      Above the Break 3  Right Side Center(RC)   
2   3PT Field Goal      Above the Break 3  Right Side Center(RC)   
3   3PT Field Goal      Above the Break 3              Center(C)   
0   3PT Field Goal      Above the Break 3   Left Side Center(LC)   
..             ...                    ...                    ...   
0   2PT Field Goal        Restricted Area              Center(C)   
0   2PT Field Goal              Mid-Range          Right Side(R)   
1   3PT Field Goal      Above the Break 3   Left Side Center(LC)   
2   2PT Field Goal        Restricted Area              Center(C)   
3   3PT Field Goal      Above the Break 3   Left Side Center(LC)   

    SHOT_ZONE_RANGE  SHOT_DISTANCE  LOC_X  LOC_Y  
0   Less Than 8 ft.            6.0  -40.0   53.0  
1           24+ ft.           26.0  182.0  195.0  
2           24+ ft.           26.0  159.0  206.0  
3           24+ ft.           27.0  -15.0  274.0  
0           24+ ft.           24.0 -149.0  198.0  
..              ...            ...    ...    ...  
0   Less Than 8 ft.            2.0  -22.0    8.0  
0         16-24 ft.           18.0  177.0   64.0  
1           24+ ft.           26.0 -201.0  167.0  
2   Less Than 8 ft.            0.0    6.0    6.0  
3           24+ ft.           25.0 -164.0  194.0  

[200963 rows x 18 columns]

In [17]:
#drop any nans and change objects data types
shot_log = shot_log.dropna()

In [18]:
shot_log.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 200963 entries, 0 to 3
Data columns (total 18 columns):
 #   Column             Non-Null Count   Dtype  
---  ------             --------------   -----  
 0   CLOSE_DEF_DIST     200963 non-null  float64
 1   DRIBBLES           200963 non-null  float64
 2   LOCATION           200963 non-null  object 
 3   PTS                200963 non-null  float64
 4   PTS_TYPE           200963 non-null  float64
 5   SHOT_DIST          200963 non-null  float64
 6   SHOT_RESULT        200963 non-null  object 
 7   TOUCH_TIME         200963 non-null  float64
 8   PLAYER_NAME        200963 non-null  object 
 9   SECONDS_REMAINING  200963 non-null  float64
 10  ACTION_TYPE        200963 non-null  object 
 11  SHOT_TYPE          200963 non-null  object 
 12  SHOT_ZONE_BASIC    200963 non-null  object 
 13  SHOT_ZONE_AREA     200963 non-null  object 
 14  SHOT_ZONE_RANGE    200963 non-null  object 
 15  SHOT_DISTANCE      200963 non-null  float64
 16  LOC_X  

In [19]:
#get a list of columns that are objects
for col in shot_log.columns:
    if shot_log[col].dtypes == 'object':
        print(col)

LOCATION
SHOT_RESULT
PLAYER_NAME
ACTION_TYPE
SHOT_TYPE
SHOT_ZONE_BASIC
SHOT_ZONE_AREA
SHOT_ZONE_RANGE


In [20]:
#  LOCATION 
# mimport labelencoder to changesex itno numerical
from sklearn.preprocessing import LabelEncoder

# get the function
encoder = LabelEncoder()
#shot_log_model = shot_log_model.copy()
shot_log['LOCATION'] = encoder.fit_transform(shot_log['LOCATION'])
# shot_log['CLOSEST_DEFENDER'] = encoder.fit_transform(shot_log['CLOSEST_DEFENDER'])
# shot_log['GRID_TYPE'] = encoder.fit_transform(shot_log['GRID_TYPE'])
shot_log['PLAYER_NAME'] = encoder.fit_transform(shot_log['PLAYER_NAME'])

shot_log['SHOT_ZONE_BASIC'] = encoder.fit_transform(shot_log['SHOT_ZONE_BASIC'])
shot_log['SHOT_ZONE_AREA'] = encoder.fit_transform(shot_log['SHOT_ZONE_AREA'])
# shot_log['SHOT_ZONE_RANGE'] = encoder.fit_transform(shot_log['SHOT_ZONE_RANGE'])

In [21]:
shot_log['ACTION_TYPE'] = encoder.fit_transform(shot_log['ACTION_TYPE'])

In [22]:
#assign numerical values to categories with 2 values only
shot_log['SHOT_TYPE'].replace(to_replace = ['2PT Field Goal', '3PT Field Goal'], value = [2,3], inplace=True)
shot_log.head()

CLOSE_DEF_DIST  DRIBBLES  LOCATION  PTS  PTS_TYPE  SHOT_DIST SHOT_RESULT  \
0             1.9      17.0         0  0.0       2.0        7.7      missed   
1             3.2       0.0         0  3.0       3.0       23.5        made   
2             3.5       0.0         0  0.0       3.0       25.7      missed   
3             3.6      19.0         0  0.0       3.0       24.7      missed   
0             3.7       0.0         1  3.0       3.0       25.2        made   

   TOUCH_TIME  PLAYER_NAME  SECONDS_REMAINING  ACTION_TYPE  SHOT_TYPE  \
0        13.5          132                6.0           21          2   
1         1.4          132                7.0           21          3   
2         1.3          132               33.0           21          3   
3        14.5          132               21.0           21          3   
0         1.0          132               41.0           21          3   

   SHOT_ZONE_BASIC  SHOT_ZONE_AREA  SHOT_ZONE_RANGE  SHOT_DISTANCE  LOC_X  \
0                2               1  Less Than 8 ft.            6.0  -40.0   
1                0               4          24+ ft.           26.0  182.0   
2                0               4          24+ ft.           26.0  159.0   
3                0               1          24+ ft.           27.0  -15.0   
0                0               2          24+ ft.           24.0 -149.0   

   LOC_Y  
0   53.0  
1  195.0  
2  206.0  
3  274.0  
0  198.0

In [23]:
#assign numerical values to categories with 2 values only
shot_log['SHOT_RESULT'].replace(to_replace = ['missed', 'made'], value = [0,1], inplace=True)
shot_log.head()

CLOSE_DEF_DIST  DRIBBLES  LOCATION  PTS  PTS_TYPE  SHOT_DIST  SHOT_RESULT  \
0             1.9      17.0         0  0.0       2.0        7.7            0   
1             3.2       0.0         0  3.0       3.0       23.5            1   
2             3.5       0.0         0  0.0       3.0       25.7            0   
3             3.6      19.0         0  0.0       3.0       24.7            0   
0             3.7       0.0         1  3.0       3.0       25.2            1   

   TOUCH_TIME  PLAYER_NAME  SECONDS_REMAINING  ACTION_TYPE  SHOT_TYPE  \
0        13.5          132                6.0           21          2   
1         1.4          132                7.0           21          3   
2         1.3          132               33.0           21          3   
3        14.5          132               21.0           21          3   
0         1.0          132               41.0           21          3   

   SHOT_ZONE_BASIC  SHOT_ZONE_AREA  SHOT_ZONE_RANGE  SHOT_DISTANCE  LOC_X  \
0                2               1  Less Than 8 ft.            6.0  -40.0   
1                0               4          24+ ft.           26.0  182.0   
2                0               4          24+ ft.           26.0  159.0   
3                0               1          24+ ft.           27.0  -15.0   
0                0               2          24+ ft.           24.0 -149.0   

   LOC_Y  
0   53.0  
1  195.0  
2  206.0  
3  274.0  
0  198.0

In [24]:
#get a list of columns that are objects
for col in shot_log.columns:
    if shot_log[col].dtypes == 'object':
        print(col)

SHOT_ZONE_RANGE


In [25]:
shot_log['SHOT_RESULT'].unique()

array([0, 1], dtype=int64)

In [26]:
shot_log['PTS'].unique()

array([0., 3., 2., 4.])

In [27]:
shot_log['SHOT_ZONE_BASIC'].unique()

array([2, 0, 4, 5, 3, 6, 1])

In [28]:
shot_log['SHOT_ZONE_AREA'].unique()

array([1, 4, 2, 3, 5, 0])

In [29]:
shot_log['SHOT_ZONE_RANGE'].unique()
#assign numerical values to categories with 2 values only
shot_log['SHOT_ZONE_RANGE'].replace(to_replace = ['16-24 ft.', '24+ ft.', 'Less Than 8 ft.', '8-16 ft.','Back Court Shot'], value = [16, 24, 8, 16, 30], inplace=True)
shot_log.head()

CLOSE_DEF_DIST  DRIBBLES  LOCATION  PTS  PTS_TYPE  SHOT_DIST  SHOT_RESULT  \
0             1.9      17.0         0  0.0       2.0        7.7            0   
1             3.2       0.0         0  3.0       3.0       23.5            1   
2             3.5       0.0         0  0.0       3.0       25.7            0   
3             3.6      19.0         0  0.0       3.0       24.7            0   
0             3.7       0.0         1  3.0       3.0       25.2            1   

   TOUCH_TIME  PLAYER_NAME  SECONDS_REMAINING  ACTION_TYPE  SHOT_TYPE  \
0        13.5          132                6.0           21          2   
1         1.4          132                7.0           21          3   
2         1.3          132               33.0           21          3   
3        14.5          132               21.0           21          3   
0         1.0          132               41.0           21          3   

   SHOT_ZONE_BASIC  SHOT_ZONE_AREA  SHOT_ZONE_RANGE  SHOT_DISTANCE  LOC_X  \
0                2               1                8            6.0  -40.0   
1                0               4               24           26.0  182.0   
2                0               4               24           26.0  159.0   
3                0               1               24           27.0  -15.0   
0                0               2               24           24.0 -149.0   

   LOC_Y  
0   53.0  
1  195.0  
2  206.0  
3  274.0  
0  198.0

In [30]:
shot_log.corr()['SHOT_RESULT'].to_frame(name = 'Correlation with SHOT_RESULT').abs().sort_values(by = 'Correlation with SHOT_RESULT', ascending = False)

Correlation with SHOT_RESULT
SHOT_RESULT                            1.000000
PTS                                    0.970603
SHOT_DISTANCE                          0.193819
SHOT_DIST                              0.188337
SHOT_ZONE_RANGE                        0.169439
LOC_Y                                  0.154389
SHOT_ZONE_BASIC                        0.154323
PTS_TYPE                               0.112751
SHOT_TYPE                              0.112738
SHOT_ZONE_AREA                         0.111448
TOUCH_TIME                             0.060824
ACTION_TYPE                            0.046170
DRIBBLES                               0.042955
SECONDS_REMAINING                      0.017723
LOCATION                               0.012986
PLAYER_NAME                            0.009704
CLOSE_DEF_DIST                         0.005649
LOC_X                                  0.000524

### Split and test

In [31]:
cr = shot_log.corr()
cr.style.background_gradient(cmap='RdBu_r').set_precision(2)
# 'RdBu_r' & 'BrBG' are other good diverging colormaps

In [32]:
# create X feature
#X = shot_log_model.drop(['SHOT_RESULT', 'FGM', 'PTS'], axis =1)
X = shot_log.drop(['SHOT_RESULT', 'PTS'], axis =1)

#create target
y = shot_log['SHOT_RESULT']

In [33]:
shot_log = pd.get_dummies(X)
shot_log

CLOSE_DEF_DIST  DRIBBLES  LOCATION  PTS_TYPE  SHOT_DIST  TOUCH_TIME  \
0              1.9      17.0         0       2.0        7.7        13.5   
1              3.2       0.0         0       3.0       23.5         1.4   
2              3.5       0.0         0       3.0       25.7         1.3   
3              3.6      19.0         0       3.0       24.7        14.5   
0              3.7       0.0         1       3.0       25.2         1.0   
..             ...       ...       ...       ...        ...         ...   
0              2.3       1.0         1       2.0        1.3         0.9   
0              1.8       2.0         0       2.0       13.7         3.2   
1              7.1       0.0         0       3.0       22.9         1.2   
2              1.1       3.0         0       2.0        3.1         3.1   
3              5.2       1.0         0       3.0       25.0         2.1   

    PLAYER_NAME  SECONDS_REMAINING  ACTION_TYPE  SHOT_TYPE  SHOT_ZONE_BASIC  \
0           132                6.0           21          2                2   
1           132                7.0           21          3                0   
2           132               33.0           21          3                0   
3           132               21.0           21          3                0   
0           132               41.0           21          3                0   
..          ...                ...          ...        ...              ...   
0           175               15.0           30          2                5   
0           175               28.0           13          2                4   
1           175               48.0           21          3                0   
2           175               56.0            8          2                5   
3           175               49.0           21          3                0   

    SHOT_ZONE_AREA  SHOT_ZONE_RANGE  SHOT_DISTANCE  LOC_X  LOC_Y  
0                1                8            6.0  -40.0   53.0  
1                4               24           26.0  182.0  195.0  
2                4               24           26.0  159.0  206.0  
3                1               24           27.0  -15.0  274.0  
0                2               24           24.0 -149.0  198.0  
..             ...              ...            ...    ...    ...  
0                1                8            2.0  -22.0    8.0  
0                5               16           18.0  177.0   64.0  
1                2               24           26.0 -201.0  167.0  
2                1                8            0.0    6.0    6.0  
3                2               24           25.0 -164.0  194.0  

[200963 rows x 16 columns]

In [34]:
X

CLOSE_DEF_DIST  DRIBBLES  LOCATION  PTS_TYPE  SHOT_DIST  TOUCH_TIME  \
0              1.9      17.0         0       2.0        7.7        13.5   
1              3.2       0.0         0       3.0       23.5         1.4   
2              3.5       0.0         0       3.0       25.7         1.3   
3              3.6      19.0         0       3.0       24.7        14.5   
0              3.7       0.0         1       3.0       25.2         1.0   
..             ...       ...       ...       ...        ...         ...   
0              2.3       1.0         1       2.0        1.3         0.9   
0              1.8       2.0         0       2.0       13.7         3.2   
1              7.1       0.0         0       3.0       22.9         1.2   
2              1.1       3.0         0       2.0        3.1         3.1   
3              5.2       1.0         0       3.0       25.0         2.1   

    PLAYER_NAME  SECONDS_REMAINING  ACTION_TYPE  SHOT_TYPE  SHOT_ZONE_BASIC  \
0           132                6.0           21          2                2   
1           132                7.0           21          3                0   
2           132               33.0           21          3                0   
3           132               21.0           21          3                0   
0           132               41.0           21          3                0   
..          ...                ...          ...        ...              ...   
0           175               15.0           30          2                5   
0           175               28.0           13          2                4   
1           175               48.0           21          3                0   
2           175               56.0            8          2                5   
3           175               49.0           21          3                0   

    SHOT_ZONE_AREA  SHOT_ZONE_RANGE  SHOT_DISTANCE  LOC_X  LOC_Y  
0                1                8            6.0  -40.0   53.0  
1                4               24           26.0  182.0  195.0  
2                4               24           26.0  159.0  206.0  
3                1               24           27.0  -15.0  274.0  
0                2               24           24.0 -149.0  198.0  
..             ...              ...            ...    ...    ...  
0                1                8            2.0  -22.0    8.0  
0                5               16           18.0  177.0   64.0  
1                2               24           26.0 -201.0  167.0  
2                1                8            0.0    6.0    6.0  
3                2               24           25.0 -164.0  194.0  

[200963 rows x 16 columns]

In [35]:
y.value_counts()

0    109610
1     91353
Name: SHOT_RESULT, dtype: int64

In [36]:
#check X
X.describe()

CLOSE_DEF_DIST       DRIBBLES       LOCATION       PTS_TYPE  \
count   200963.000000  200963.000000  200963.000000  200963.000000   
mean         4.183973       1.920339       0.499450       2.259262   
std          2.726702       3.408023       0.500001       0.438231   
min          0.000000       0.000000       0.000000       2.000000   
25%          2.300000       0.000000       0.000000       2.000000   
50%          3.700000       0.000000       0.000000       2.000000   
75%          5.300000       2.000000       1.000000       3.000000   
max         52.300000      34.000000       1.000000       3.000000   

           SHOT_DIST     TOUCH_TIME    PLAYER_NAME  SECONDS_REMAINING  \
count  200963.000000  200963.000000  200963.000000      200963.000000   
mean       13.486102       2.624204     240.593348          28.738141   
std         8.896573       2.907081     136.149997          17.459695   
min         0.000000     -23.000000       0.000000           0.000000   
25%         4.700000       0.800000     123.000000          14.000000   
50%        13.400000       1.400000     245.000000          29.000000   
75%        22.400000       3.500000     355.000000          44.000000   
max        46.800000      24.700000     478.000000          59.000000   

         ACTION_TYPE      SHOT_TYPE  SHOT_ZONE_BASIC  SHOT_ZONE_AREA  \
count  200963.000000  200963.000000    200963.000000   200963.000000   
mean       21.716062       2.259232         3.281818        2.113787   
std         8.671088       0.438214         1.907470        1.439883   
min         0.000000       2.000000         0.000000        0.000000   
25%        21.000000       2.000000         2.000000        1.000000   
50%        21.000000       2.000000         4.000000        1.000000   
75%        22.000000       3.000000         5.000000        3.000000   
max        49.000000       3.000000         6.000000        5.000000   

       SHOT_ZONE_RANGE  SHOT_DISTANCE          LOC_X          LOC_Y  
count    200963.000000  200963.000000  200963.000000  200963.000000  
mean         14.713216      12.303230      -0.449496      80.807606  
std           6.501800       9.848454     109.038567      87.439261  
min           8.000000       0.000000    -250.000000     -51.000000  
25%           8.000000       2.000000     -54.000000       9.000000  
50%          16.000000      13.000000       1.000000      41.000000  
75%          24.000000      22.000000      51.000000     153.000000  
max          30.000000      86.000000     250.000000     865.000000

In [37]:
# Split the X and y into X_train, X_test, y_train, y_test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [38]:
# Check output
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(150722, 16)
(50241, 16)
(150722,)
(50241,)


## Balanced Random Forest Classifier

In [39]:
# Resample the training data with the BalancedRandomForestClassifier
# keep random_state at 1
from imblearn.ensemble import BalancedRandomForestClassifier
balanced_random_forest = BalancedRandomForestClassifier(n_estimators=100, random_state=1)

In [40]:
# Calculated the balanced accuracy score
balanced_random_forest.fit(X_train, y_train) 
y_pred = balanced_random_forest.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.6414515435950459

In [41]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[19338,  8032],
       [ 9689, 13182]], dtype=int64)

In [42]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.67      0.71      0.58      0.69      0.64      0.41     27370
          1       0.62      0.58      0.71      0.60      0.64      0.40     22871

avg / total       0.65      0.65      0.64      0.65      0.64      0.41     50241



In [43]:
# List the features sorted in descending order by feature importance

with pd.option_context('display.max_rows', None, 'display.max_columns', None): 
    feature_importance = pd.Series(balanced_random_forest.feature_importances_,index=shot_log.columns).sort_values(ascending=False)
    print(feature_importance)

SHOT_DIST            0.125024
PLAYER_NAME          0.122127
CLOSE_DEF_DIST       0.112792
SECONDS_REMAINING    0.109753
LOC_X                0.108400
LOC_Y                0.107548
TOUCH_TIME           0.100503
ACTION_TYPE          0.065590
SHOT_DISTANCE        0.064353
DRIBBLES             0.034338
LOCATION             0.018630
SHOT_ZONE_BASIC      0.014009
SHOT_ZONE_AREA       0.011291
SHOT_ZONE_RANGE      0.003594
SHOT_TYPE            0.001185
PTS_TYPE             0.000862
dtype: float64


## Easy Ensemble AdaBoost Classifier

In [44]:
# Train the EasyEnsembleClassifier
# keep random_state at 1
from imblearn.ensemble import EasyEnsembleClassifier
easy_ensemble = EasyEnsembleClassifier(random_state=1)
easy_ensemble.fit(X_train, y_train) 
y_pred = easy_ensemble.predict(X_test)

In [45]:
# Calculated the balanced accuracy score
balanced_accuracy_score(y_test, y_pred)

0.643751687655727

In [46]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[20523,  6847],
       [10574, 12297]], dtype=int64)

In [47]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.66      0.75      0.54      0.70      0.63      0.41     27370
          1       0.64      0.54      0.75      0.59      0.63      0.39     22871

avg / total       0.65      0.65      0.63      0.65      0.63      0.40     50241



## Previous model

### Scale our data

In [48]:
# scale the data. Preprocessing 
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [49]:
# fit the data. then transform
X_scaler = scaler.fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [50]:
X_train_scaled


array([[ 2.46937687, -0.56342693, -1.00115511, ...,  0.7811083 ,
        -1.84009468, -1.03817682],
       [-0.28761012,  0.02625399,  0.99884622, ...,  0.3750339 ,
        -1.26198816,  0.04726908],
       [-0.14057081,  0.02625399,  0.99884622, ..., -0.03104049,
        -1.14269634, -0.91249361],
       ...,
       [-0.98604682,  0.02625399,  0.99884622, ..., -1.04622647,
        -0.21589064, -0.82108764],
       [-1.35364509, -0.56342693,  0.99884622, ..., -1.04622647,
         0.19704259, -0.92391936],
       [-0.98604682,  0.02625399, -1.00115511, ..., -0.33559628,
        -0.68388163, -0.23837458]])

In [51]:
X_test_scaled

array([[-6.55208386e-01,  9.10775370e-01,  9.98846222e-01, ...,
        -9.44707876e-01,  9.61033574e-02, -5.81146968e-01],
       [-6.91968212e-01,  2.62539896e-02,  9.98846222e-01, ...,
        -1.04622647e+00,  1.87866298e-01, -7.63958908e-01],
       [-1.09632630e+00,  3.21094450e-01,  9.98846222e-01, ...,
        -9.44707876e-01, -1.70009169e-01, -6.38275699e-01],
       ...,
       [ 5.04256473e+00, -5.63426931e-01, -1.00115511e+00, ...,
         1.08566409e+00,  2.11488804e+00, -9.46770849e-01],
       [-1.05956648e+00,  3.21094450e-01, -1.00115511e+00, ...,
        -5.38633482e-01,  4.34041715e-03, -1.12691371e-01],
       [ 1.90267625e-01,  6.15934910e-01,  9.98846222e-01, ...,
        -3.35596285e-01, -7.38939399e-01, -4.21186520e-01]])

## Build a Model

In [52]:
from sklearn.tree import DecisionTreeClassifier

In [53]:
model = DecisionTreeClassifier()
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)

# model = DecisionTreeClassifier()
# model.fit(X_train, y_train)
# y_pred = model.predict(X_test)

In [54]:
from sklearn.metrics import classification_report
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.61      0.60      0.61     27370
           1       0.53      0.54      0.54     22871

    accuracy                           0.57     50241
   macro avg       0.57      0.57      0.57     50241
weighted avg       0.57      0.57      0.57     50241

